# Generated by Django 4.2.6 on 2024-06-18 19:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invest_projects', '0010_alter_item_count_add_favorite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=300)),
                ('profile_status', models.CharField(blank=True, max_length=200, null=True)),
                ('interest', models.CharField(max_length=50)),
                ('avatar', models.ImageField(blank=True, max_length=500, null=True, upload_to='profile_avatars')),
                ('profile_info', models.TextField(blank=True, null=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('phone_verified', models.BooleanField(default=False)),
                ('snils', models.ImageField(blank=True, null=True, upload_to='profile_snils')),
                ('passport', models.ImageField(blank=True, null=True, upload_to='profile_passport')),
                ('ogrn', models.ImageField(blank=True, null=True, upload_to='profile_ogrn')),
                ('inn', models.ImageField(blank=True, null=True, upload_to='profile_inn')),
                ('last_acivity', models.DateTimeField(default=django.utils.timezone.now)),
                ('favorites', models.ManyToManyField(blank=True, to='invest_projects.item')),
            ],
        ),
        migrations.CreateModel(
            name='SupportMail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile_imgs')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.profile')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='images',
            field=models.ManyToManyField(related_name='images_for_profile', to='account.profileimage'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
