# Generated by Django 4.2.5 on 2023-09-26 17:22

import account.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('invest_projects', '0003_item_paid_verification'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportMail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest', models.CharField(max_length=50)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=account.models.save_image)),
                ('profile_info', models.TextField(blank=True, null=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('phone_verified', models.BooleanField(default=False)),
                ('snils', models.ImageField(blank=True, null=True, upload_to=account.models.save_image)),
                ('passport', models.ImageField(blank=True, null=True, upload_to=account.models.save_image)),
                ('ogrn', models.ImageField(blank=True, null=True, upload_to=account.models.save_image)),
                ('inn', models.ImageField(blank=True, null=True, upload_to=account.models.save_image)),
                ('last_acivity', models.DateTimeField(default=datetime.datetime(2023, 9, 26, 20, 22, 33, 483321))),
                ('favorites', models.ManyToManyField(blank=True, null=True, to='invest_projects.item')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
