# Generated by Django 4.2.6 on 2024-06-18 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='images',
            field=models.ManyToManyField(blank=True, null=True, related_name='images_for_profile', to='account.profileimage'),
        ),
    ]
