# Generated by Django 4.2.5 on 2023-10-01 17:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='last_acivity',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 1, 20, 59, 3, 85259)),
        ),
    ]
