# Generated by Django 4.2.6 on 2024-12-24 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_profile_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='about_user',
            field=models.TextField(default='Нет'),
        ),
        migrations.AddField(
            model_name='profile',
            name='about_user_sub_info',
            field=models.TextField(default='Нет'),
        ),
        migrations.AddField(
            model_name='profile',
            name='branch',
            field=models.CharField(default='Нет', max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='company',
            field=models.CharField(default='Нет', max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='position_on_company',
            field=models.CharField(default='Нет', max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='site_company',
            field=models.CharField(default='Нет', max_length=200),
        ),
    ]
