# Generated by Django 4.2.5 on 2023-10-04 19:46

import account.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_profile_profile_status_alter_profile_avatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=account.models.save_image),
        ),
        migrations.AlterField(
            model_name='profile',
            name='inn',
            field=models.ImageField(blank=True, null=True, upload_to=account.models.save_image),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_acivity',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 4, 22, 46, 8, 749044)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='ogrn',
            field=models.ImageField(blank=True, null=True, upload_to=account.models.save_image),
        ),
        migrations.AlterField(
            model_name='profile',
            name='passport',
            field=models.ImageField(blank=True, null=True, upload_to=account.models.save_image),
        ),
        migrations.AlterField(
            model_name='profile',
            name='snils',
            field=models.ImageField(blank=True, null=True, upload_to=account.models.save_image),
        ),
    ]
