# Generated by Django 4.2.6 on 2024-12-24 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_profile_about_user_profile_about_user_sub_info_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_info',
        ),
    ]
