# Generated by Django 4.2.6 on 2024-12-24 15:53

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_profilevideo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilevideo',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='profile_videos', validators=[account.models.validate_video_extension]),
        ),
    ]
