# Generated by Django 4.2.5 on 2023-09-13 21:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('invest_projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='count_add_favorite',
            field=models.ManyToManyField(blank=True, null=True, related_name='favorite_items', to=settings.AUTH_USER_MODEL),
        ),
    ]
