# Generated by Django 4.2.5 on 2023-09-15 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest_projects', '0002_alter_item_count_add_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='paid_verification',
            field=models.BooleanField(default=False),
        ),
    ]
