# Generated by Django 4.2.5 on 2023-10-01 17:59

from django.db import migrations, models
import invest_projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('invest_projects', '0003_item_paid_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to=invest_projects.models.save_image),
        ),
        migrations.AddField(
            model_name='item',
            name='project_avatar',
            field=models.ImageField(blank=True, null=True, upload_to=invest_projects.models.save_image),
        ),
    ]
