# Generated by Django 4.2.5 on 2023-10-04 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest_projects', '0005_alter_itemimage_item_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemimage',
            name='item_id',
            field=models.IntegerField(default=-1),
        ),
    ]
