# Generated by Django 4.2.6 on 2023-10-26 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest_projects', '0007_alter_itemimage_item_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='author_job_title',
            field=models.CharField(default='Директор', max_length=200),
        ),
        migrations.AddField(
            model_name='item',
            name='profit_parametr',
            field=models.CharField(default='Месяц', max_length=100),
        ),
    ]
