# Generated by Django 4.2.6 on 2023-10-26 23:50

from django.db import migrations, models
import invest_projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('invest_projects', '0008_item_author_job_title_item_profit_parametr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='background_image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=invest_projects.models.save_image),
        ),
        migrations.AlterField(
            model_name='item',
            name='project_avatar',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=invest_projects.models.save_image),
        ),
        migrations.AlterField(
            model_name='itemimage',
            name='image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=invest_projects.models.save_image),
        ),
    ]
