# Generated by Django 4.2.6 on 2024-06-18 19:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('invest_projects', '0009_alter_item_background_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='count_add_favorite',
            field=models.ManyToManyField(blank=True, related_name='favorite_items', to=settings.AUTH_USER_MODEL),
        ),
    ]
