# Generated by Django 4.2.6 on 2024-12-24 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invest_projects', '0011_remove_item_category_item_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='profit_per_month',
            new_name='profit_number',
        ),
    ]
