# Generated by Django 4.2.6 on 2024-12-24 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest_projects', '0012_rename_profit_per_month_item_profit_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='profit',
            field=models.BooleanField(default=False),
        ),
    ]
